### ISSUE TITLE
Wrong variable name on readme

### ISSUE THREAD

**Issue by miguelcastilho** [nuagenetworks/nuage-neutron-sync#5]
The Readme states there is a variable called `excluded_tenants` but in the configuration file `config/nuage-neutron-sync.conf` the variable is called `excluded_enterprises`.

**Comment by dieterdm** [comment]
Thanks for reporting. Changed in https://github.com/nuagenetworks/nuage-neutron-sync/commit/5a57591339d72bb9dc9444b9bca4baec60ed5792
