### ISSUE TITLE
L2 Domains sync function re-creates openstack subnets

### ISSUE THREAD

**Issue by ikbalcam** [nuagenetworks/nuage-neutron-sync#7]
Using this tool in my lab with Ocata and Nuage 5.2.3.

Each time the script invoked, Openstack subnets related to Nuage L2 Domains gets deleted in Openstack and re-created. It claims that VSD subnet has changed. I don't think it's true. 

Note: Nuage L2 Domains are Unmanaged (Unnumbered - No DHCP). 

Excerpts from the script execution. 
```
DEBUG:nuage-neutron-sync:Gateway IP of subnet 1b872c5c-d1f7-48d8-8254-ac3fedd19302 ("link1") changed to None
INFO:nuage-neutron-sync:VSD subnet 1b872c5c-d1f7-48d8-8254-ac3fedd19302 has changed. Deleting mapped OpenStack subnet 4e9d5ec7-e619-49f8-a9fb-0781a5ead335
DEBUG:nuage-neutron-sync:Creating network with body {'network': {'tenant_id': u'557c8dfb33394ec88925c5fbfea95af1', 'name': u'link1', 'admin_state_up': True}}
DEBUG:nuage-neutron-sync:Creating subnet with body {'subnets': [{'name': u'link1', 'enable_dhcp': False, 'network_id': u'6177a1d4-6340-43d6-8e4a-9b974fb53389', 'tenant_id': u'557c8dfb33394ec88925c5fbfea95af1', 'net_partition': u'Demo', 'ip_version': 4, 'cidr': '127.0.0.0/8', 'nuagenet': u'1b872c5c-d1f7-48d8-8254-ac3fedd19302'}]}
INFO:nuage-neutron-sync:Created neutron subnet link1
```

**Comment by pdellaert** [comment]
@ikbalcam, just an FYI: this is a non-supported tool from Nuage as an example and has only been tested with OpenStack Pike... That means that unless someone feels the urge to fix/test this with Ocata, i'm not sure we'll get to it anytime soon

Additionally, I don't think this is meant to be used with Unmanaged L2 domains
